# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - venv/
    

stages:
  - build
#  - deploy

build:
  stage: build
  tags:
    - shared-fi
    
    
  before_script:
    - python -V               # Print out python version for debugging
    - pip install virtualenv
    - git submodule update --remote --merge
    - virtualenv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
      
  script:
    - python generate_pdf.py
    
  artifacts:
    paths:
      - stack_overflow.pdf
      

#pages:
#  stage: deploy
#  tags:
#    - shared-fi
#    
#  script:
#    - mkdir public
#    - cp stack_overflow.pdf public/stack_overflow.pdf
#  artifacts:
#    paths:
#      - public
